<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- xUnit.net v3 test projects are executables. -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Identity\Quart.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Workplaces\Quart.Modules.Workplaces.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Scheduling\Quart.Modules.Scheduling.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Marketplace\Quart.Modules.Marketplace.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Announcements\Quart.Modules.Announcements.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Files\Quart.Modules.Files.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Notifications\Quart.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\src\backend\Modules\Quart.Modules.Jobs\Quart.Modules.Jobs.csproj" />
    <ProjectReference Include="..\..\src\backend\Quart.Generator\Quart.Generator.csproj" />
  </ItemGroup>
</Project>
