/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/meta': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetMeta'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/lab/scenarios/presotea': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetLabPresoteaScenario'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/lab/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['GenerateLabSchedule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiProblem: {
      code: string;
      traceId: string;
      /** Format: int32 */
      status: number;
      type?: null | string;
      title?: null | string;
      detail?: null | string;
      instance?: null | string;
      errors?:
        | null
        | {
            code: string;
            path: string;
          }[];
    };
    Assignment: {
      shiftId: string;
      memberId: string;
    };
    ConflictPair: {
      blockId: string;
      memberA: string;
      memberB: string;
    };
    GeneratorInput: {
      shifts: components['schemas']['GeneratorShift'][];
      members: components['schemas']['GeneratorMember'][];
      availability: components['schemas']['MemberAvailability'][];
      lockedAssignments: components['schemas']['Assignment'][];
      conflictPairs: components['schemas']['ConflictPair'][];
      rules: components['schemas']['GeneratorRules'];
      /** Format: int32 */
      seed: number;
    };
    GeneratorIssue: {
      code: string;
      shiftIds: string[];
      memberIds: string[];
      parameters: {
        [key: string]: string;
      };
    };
    GeneratorMember: {
      id: string;
      /** Format: int32 */
      level: number;
      /** Format: double */
      desiredWeeklyHours: number;
      /** Format: double */
      maxWeeklyHours: null | number;
    };
    GeneratorResult: {
      assignments: components['schemas']['Assignment'][];
      issues: components['schemas']['GeneratorIssue'][];
      /** Format: int32 */
      score: number;
      /** Format: int32 */
      seed: number;
    };
    GeneratorRules: {
      /** Format: int32 */
      maxConsecutiveShifts: null | number;
      openingFairness: boolean;
      closingFairness: boolean;
    };
    GeneratorShift: {
      id: string;
      blockId: string;
      /** Format: date */
      date: string;
      /** Format: time */
      start: string;
      /** Format: time */
      end: string;
      /** Format: int32 */
      headcount: number;
      levelRequirements: components['schemas']['LevelRequirement'][];
    };
    LabPerson: {
      id: string;
      name: string;
    };
    LabScenario: {
      name: string;
      people: components['schemas']['LabPerson'][];
      input: components['schemas']['GeneratorInput'];
    };
    LevelRequirement: {
      /** Format: int32 */
      level: number;
      /** Format: int32 */
      minCount: number;
    };
    MemberAvailability: {
      memberId: string;
      submitted: boolean;
      shiftIds: string[];
    };
    MetaResponse: {
      name: string;
      version: string;
      environment: string;
      /** Format: date-time */
      serverTimeUtc: string;
      database: string;
      /** Format: date-time */
      lastTickAt: null | string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetMeta: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetaResponse'];
        };
      };
      /** @description Any error, as problem details with a machine-readable code (AD-023). */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ApiProblem'];
        };
      };
    };
  };
  GetLabPresoteaScenario: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LabScenario'];
        };
      };
      /** @description Any error, as problem details with a machine-readable code (AD-023). */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ApiProblem'];
        };
      };
    };
  };
  GenerateLabSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GeneratorInput'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GeneratorResult'];
        };
      };
      /** @description Any error, as problem details with a machine-readable code (AD-023). */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ApiProblem'];
        };
      };
    };
  };
}
